# Generated by Django 2.2.2 on 2019-06-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.IntegerField()),
                ('studentname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=200)),
                ('address', models.TextField()),
            ],
        ),
    ]
