# Generated by Django 2.2.2 on 2019-06-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='studentid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
